### ISSUE TITLE
MP4 to WebM - Encoding Failed

### ISSUE THREAD

**Issue by tuckerdarby** [pascalbaljetmedia/laravel-ffmpeg#10]
Hello,

I've been attempting to convert MP4 videos to WebM, but am having issues. When I try this with native FFMpeg it works fine, but fails when using this Laravel plugin.
Here is a snippet of my code:
```
    $webm_format = new FFMpeg\Format\Video\WebM();
    $video->save($webm_format, '/var/www/html/laravel/storage/'.$webm_target_name);

```
And here is my stack trace:
```
#0 [internal function]: FFMpeg\Media\Video->save(Object(FFMpeg\Format\Video\WebM), '/var/www/html/l...')
#1 /var/www/html/laravel/vendor/pbmedia/laravel-ffmpeg/src/Media.php(107): call_user_func_array(Array, Array)
#2 /var/www/html/laravel/app/Jobs/TranscodeProcess.php(80): Pbmedia\LaravelFFMpeg\Media->__call('save', Array)
#3 [internal function]: App\Jobs\TranscodeProcess->handle()
#4 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#9 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\TranscodeProcess))
#10 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\TranscodeProcess))
#11 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(42): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\TranscodeProcess), false)
#13 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(69): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#14 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(291): Illuminate\Queue\Jobs\Job->fire()
#15 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(258): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#16 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(110): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#17 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#18 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(83): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#19 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#20 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#21 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#22 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#23 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#24 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#25 /var/www/html/laravel/vendor/symfony/console/Command/Command.php(265): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#26 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#27 /var/www/html/laravel/vendor/symfony/console/Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/laravel/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/laravel/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/laravel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}1
```

Right before this I am doing an X264 encoding with audio codec of "libfdk_aac", and it works fine.

I have also noticed this does not happen with all videos. (Works with videos originating from iPhones, but not Androids)

Let me know if there's more information I can provide.

Help is greatly appreciated.

**Comment by pascalbaljet** [comment]
The ```save``` method only requires a filename, you should call the ```inFormat``` method on the Exporter:

```php
$video = FFMpeg::open('my_movie.mov');
$webm_format = new FFMpeg\Format\Video\WebM();

$video->export()
    ->inFormat($webm_format)
    ->save('my_movie.webm')
```

Check out the README for more examples.

**Comment by tuckerdarby** [comment]
Thank you for the quick reply. We've decided to drop WebM support, so this isn't much of an issue anymore.

However, when I tried out your examples with export(), I get the error:

`PHP error:  Call to undefined method FFMpeg\Media\Video::export() on line 1`

This could be user error or a problem with the version of the plugin I have. Just thought I'd post a follow up though.
