### ISSUE TITLE
Multiple instance of FFMpeg issue

### ISSUE THREAD

**Issue by jefrisingh** [pascalbaljetmedia/laravel-ffmpeg#204]
I want to generate thumnail of a video then I need to convert the video to HLS formate, Both are working fine without any issue if they are executed separatly , i.e, If I comment video convertion code then thumnail generation will work fine, If I comment thumnail generation code then video converion code will work If I uncomment both then the second FFMpeg process will have error, I'll attach the log, and Here is the code

```
<?php

namespace App\Jobs;

use FFMpeg;
use App\Video;
use FFMpeg\Format\Video\X264;
use FFMpeg\Filters\AdvancedMedia\ComplexFilters;
use FFMpeg\Filters\Video\WatermarkFilter;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class ConvertForStreaming implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $video;
    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(Video $video)
    {
        $this->video = $video->withoutRelations();
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {

       FFMpeg::fromDisk('local')
            ->open($this->video->path)
            ->getFrameFromSeconds(1)
            ->export()
            ->toDisk('local')
            ->save("public/thumbnails/{$this->video->id}.png");

        $this->video->update([
            'thumbnail' => Storage::url("public/thumbnails/{$this->video->id}.png")
        ]);

       $low = (new X264('aac'))->setKiloBitrate(100);
       $mid = (new X264('aac'))->setKiloBitrate(250);
       $high = (new X264('aac'))->setKiloBitrate(500);

       FFMpeg::fromDisk('local')
        ->open($this->video->path)
        ->exportForHLS()
        ->addFormat($low)
        ->addFormat($mid)
        ->addFormat($high)
        ->save("public/videos/{$this->video->id}/{$this->video->id}.m3u8");

        $this->video->update([
            'processed' => true,
        ]);
    }
}
```

And here is the error log

TypeError: Argument 1 passed to ProtoneMedia\LaravelFFMpeg\FFMpeg\AdvancedOutputMapping::apply() must be an instance of FFMpeg\Media\AdvancedMedia, instance of FFMpeg\Media\Frame given, called in /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php on line 60 in file /home/zerofalse/Documents/jefri/TamTam/vendor/pbmedia/laravel-ffmpeg/src/FFMpeg/AdvancedOutputMapping.php on line 50

#0 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(60): ProtoneMedia\LaravelFFMpeg\FFMpeg\AdvancedOutputMapping->apply(Object(FFMpeg\Media\Frame))
#1 [internal function]: Illuminate\Support\HigherOrderCollectionProxy->Illuminate\Support\{closure}(Object(ProtoneMedia\LaravelFFMpeg\FFMpeg\AdvancedOutputMapping), 0)
#2 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#3 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Support/HigherOrderCollectionProxy.php(61): Illuminate\Support\Collection->map(Object(Closure))
#4 /home/zerofalse/Documents/jefri/TamTam/vendor/pbmedia/laravel-ffmpeg/src/Exporters/MediaExporter.php(145): Illuminate\Support\HigherOrderCollectionProxy->__call('apply', Array)
#5 /home/zerofalse/Documents/jefri/TamTam/vendor/pbmedia/laravel-ffmpeg/src/Exporters/MediaExporter.php(104): ProtoneMedia\LaravelFFMpeg\Exporters\MediaExporter->saveWithMappings()
#6 /home/zerofalse/Documents/jefri/TamTam/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(205): ProtoneMedia\LaravelFFMpeg\Exporters\MediaExporter->save()
#7 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Support/Traits/EnumeratesValues.php(664): ProtoneMedia\LaravelFFMpeg\Exporters\HLSExporter->ProtoneMedia\LaravelFFMpeg\Exporters\{closure}(Object(Illuminate\Support\Collection))
#8 /home/zerofalse/Documents/jefri/TamTam/vendor/pbmedia/laravel-ffmpeg/src/Exporters/HLSExporter.php(215): Illuminate\Support\Collection->pipe(Object(Closure))
#9 /home/zerofalse/Documents/jefri/TamTam/app/Jobs/ConvertForStreaming.php(74): ProtoneMedia\LaravelFFMpeg\Exporters\HLSExporter->save('public/videos/2...')
#10 [internal function]: App\Jobs\ConvertForStreaming->handle()
#11 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#12 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#17 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertForStreaming))
#18 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertForStreaming))
#19 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertForStreaming), false)
#21 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ConvertForStreaming))
#22 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertForStreaming))
#23 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\SyncJob), Object(App\Jobs\ConvertForStreaming))
#25 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#26 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#27 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\ConvertForStreaming))
#28 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\ConvertForStreaming))
#29 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\ConvertForStreaming))
#30 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(134): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\ConvertForStreaming))
#31 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(17): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#32 /home/zerofalse/Documents/jefri/TamTam/app/Jobs/ConvertVideoThumbnail.php(47): App\Jobs\ConvertForStreaming::dispatch(Object(App\Video))
#33 [internal function]: App\Jobs\ConvertVideoThumbnail->handle()
#34 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(33): call_user_func_array(Array, Array)
#35 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#36 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(91): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#37 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#38 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Container/Container.php(592): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#39 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#40 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ConvertVideoThumbnail))
#41 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoThumbnail))
#42 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ConvertVideoThumbnail), false)
#44 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ConvertVideoThumbnail))
#45 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ConvertVideoThumbnail))
#46 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\SyncJob), Object(App\Jobs\ConvertVideoThumbnail))
#48 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#49 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#50 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(182): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\ConvertVideoThumbnail))
#51 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(158): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\ConvertVideoThumbnail))
#52 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\ConvertVideoThumbnail))
#53 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(134): Illuminate\Bus\Dispatcher->dispatch(Object(App\Jobs\ConvertVideoThumbnail))
#54 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(17): Illuminate\Foundation\Bus\PendingDispatch->__destruct()
#55 /home/zerofalse/Documents/jefri/TamTam/app/Http/Controllers/VideoController.php(53): App\Jobs\ConvertVideoThumbnail::dispatch(Object(App\Video))
#56 [internal function]: App\Http\Controllers\VideoController->uploadVideo(Object(Illuminate\Http\Request))
#57 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#58 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('uploadVideo', Array)
#59 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\VideoController), 'uploadVideo')
#60 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#61 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#62 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 60, '1')
#67 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#69 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#72 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#73 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#74 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#75 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#76 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#84 /home/zerofalse/Documents/jefri/TamTam/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /home/zerofalse/Documents/jefri/TamTam/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#90 /home/zerofalse/Documents/jefri/TamTam/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#91 /home/zerofalse/Documents/jefri/TamTam/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#92 /home/zerofalse/Documents/jefri/TamTam/server.php(21): require_once('/home/zerofalse...')
#93 {main}

**Comment by pascalbaljet** [comment]
Did you update to the latest version? I think v7.0.3 patched this.

**Comment by Akashpatil7596** [comment]
> Did you update to the latest version? I think v7.0.3 patched this.

Is resizing thumbnails can work in ffmpef V5.0?

**Comment by MrAlekhin** [comment]
having the same issue on `v7.8.1`

```
Argument 1 passed to ProtoneMedia\LaravelFFMpeg\FFMpeg\AdvancedOutputMapping::apply() must be an instance of FFMpeg\Media\AdvancedMedia, instance of ProtoneMedia\LaravelFFMpeg\FFMpeg\VideoMedia given
```
