### ISSUE TITLE
Unable to load FFMpeg/

### ISSUE THREAD

**Issue by SurandraP** [pascalbaljetmedia/laravel-ffmpeg#477]
Unable to load FFMpeg(Window 10 using wamp server)
 And I am running it from docker.
 
 My executable files path :C:\ffmpeg\ffmpeg-master-latest-win64-gpl\bin\ffmpeg.exe and also set path at system environment variable
 I also tried adding executable file inside bin folder of wamp (C:/wamp64/bin/ffmpeg.exe) but still same error.

**Comment by BeiAduo** [comment]
macbook test every thinking good, when i upload to ubuntu 


[2023-04-30 15:18:23] local.INFO: ffprobe running command '/usr/local/bin/ffprobe' '-help' '-loglevel' 'quiet'  
[2023-04-30 15:18:23] local.INFO: ffprobe executed command successfully  
[2023-04-30 15:18:23] local.INFO: ffprobe running command '/usr/local/bin/ffprobe' '/tmp/phpK1A3Cj' '-show_streams' '-print_format' 'json'  
[2023-04-30 15:18:23] local.INFO: ffprobe executed command successfully  
[2023-04-30 15:18:23] local.INFO: ffmpeg running command '/usr/local/bin/ffmpeg' '-y' '-ss' '00:00:10.00' '-i' '/tmp/phpK1A3Cj' '-vframes' '1' '-f' 'image2' '/www/wwwroot/ads.dopemv.com/storage/app/public/file/vjYS9ckPgYu4M2PojDaCSU5NshjSmTYRwz6CqV5s.mp4.jpg'  
[2023-04-30 15:18:23] local.INFO: ffmpeg executed command successfully  
[2023-04-30 15:18:23] local.ERROR: Unable to load FFProbe {"userId":1,"exception":"[object] (FFMpeg\\Exception\\ExecutableNotFoundException(code: 0): Unable to load FFProbe at /www/wwwroot/ads.dopemv.com/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php:50)
[stacktrace]
#0 /www/wwwroot/ads.dopemv.com/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(220): FFMpeg\\Driver\\FFProbeDriver::create()
#1 /www/wwwroot/ads.dopemv.com/app/Observers/FileObserver.php(41): FFMpeg\\FFProbe::create()
#2 /www/wwwroot/ads.dopemv.com/vendor/laravel/nova/src/Nova.php(259): App\\Observers\\FileObserver->App\\Observers\\{
